### ISSUE TITLE
 Failure on fedora

### ISSUE THREAD

**Issue by jitka** [openlobby/demo#1]
`jitka@kren:~/git/demo $ sudo dnf in docker-compose`

`jitka@kren:~/git/demo $ make run
docker-compose up -d
ERROR: Couldn't connect to Docker daemon at http+docker://localunixsocket - is it running?
If it's at a non-standard location, specify the URL with the DOCKER_HOST environment variable.
make: *** [Makefile:2: run] Error 1`

**Comment by JanBednarik** [comment]
Is Docker daemon running? Works commands like `$ docker ps`?

**Comment by jitka** [comment]
No, how to run it?

**Comment by JanBednarik** [comment]
I don't use Fedora. Here is official Docker installation manual for Fedora: https://docs.docker.com/engine/installation/linux/docker-ce/fedora/

Here are some post installation steps to be able to run Docker commands without sudo: https://docs.docker.com/engine/installation/linux/linux-postinstall/

And here is installation info for Docker Compose: https://docs.docker.com/compose/install/

**Comment by jitka** [comment]
I run the deamon by 
`systemctl start docker`
then run the `make` under the root.
